options:
  logging: CLOUD_LOGGING_ONLY # Use only Cloud Logging to avoid bucket errors

steps:
  # Step 1: Build Docker image with tag including latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:latest', '.']

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app:latest']

  # Step 3: Get GKE credentials (authenticate kubectl)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials standard-gke-cluster --region us-central1 --project $PROJECT_ID

  # Step 4: Update deployment image to new image tag to trigger rollout
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        'image',
        'deployment/flask-app',
        'flask-app=gcr.io/$PROJECT_ID/flask-app:latest',
      ]

  # Step 5: Apply service manifest (optional, if service needs update)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/service.yaml']
